#Imports
import arcade

#Native Sprite Sizes
SPRITE_IMAGE_SIZE = 128

#Sprite Sizing
SPRITE_SCALING_PLAYER   = 0.5
SPRITE_SCALING_TILES    = 0.5
SPRITE_SIZE_PLAYER      = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING_PLAYER)
SPRITE_SIZE_TILES       = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING_TILES)

#Screen Settings
SCREEN_TITLE        = "Test platformer"
SCREEN_BACK_COLOUR  = arcade.color.ALMOND
SCREEN_GRID_WIDTH   = 25 
SCREEN_GRID_HEIGHT  = 15 
SCREEN_WIDTH        = SPRITE_SIZE_TILES * SCREEN_GRID_WIDTH
SCREEN_HEIGHT       = SPRITE_SIZE_TILES * SCREEN_GRID_HEIGHT

#Map Settings
MAP_PATH = "assets/tilemap/"